evolve-forms/main/default/objects/Conditional_Warning__mdt/Conditional_Warning__mdt.object-meta.xml
<CustomObject>
    <description>Used to provide a conditional warning before a record is saved when using Evolve dynamic forms.</description>
    <label>Conditional Warning</label>
    <pluralLabel>Conditional Warnings</pluralLabel>
</CustomObject>

evolve-forms/main/default/objects/Conditional_Warning__mdt/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <description>Enter the API name of a Flow which will be used to evaluate this warning. The flow must have an input variable called &quot;record&quot; of type sObject record and an output variable called &quot;errorMessage&quot; of type string.</description>
    <inlineHelpText>Enter the API name of a Flow which will be used to evaluate this warning. The flow must have an input variable called &quot;record&quot; of type sObject record and an output variable called &quot;errorMessage&quot; of type string.</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

evolve-forms/main/default/objects/Conditional_Warning__mdt/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>SObject API Name</description>
    <inlineHelpText>SObject API Name</inlineHelpText>
    <label>SObject API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

evolve-forms/main/default/classes/DynamicFormsController.cls
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @group - Controller
 * @description - Controller class for dynamicFormsPageLayout LWC
 */
@SuppressWarnings(
  'PMD.StdCyclomaticComplexity, PMD.CyclomaticComplexity, PMD.CognitiveComplexity, PMD.ExcessivePublicCount'
)
public with sharing class DynamicFormsController {
  private static final String CREATED_BY_ID = 'CreatedById';
  private static final String CREATED_DATE = 'CreatedDate';
  private static final String DATE_STRING = 'Date';
  private static final String DATE_TIME_STRING = 'DateTime';
  private static final String ESCAPED_PERIOD = '\\.';
  private static final String ESCAPED_QUOTE = '\'';
  private static final String GET = 'GET';
  @TestVisible
  private static final String INVALID_INPUT = 'Both `record` and `flowApiName` are required to call `DynamicFormsController.evaluateConditionalWarning`';
  private static final String LAST_MODIFIED_BY_ID = 'LastModifiedById';
  private static final String LAST_MODIFIED_DATE = 'LastModifiedDate';
  @TestVisible
  private static final String MAP_KEY_API_NAMES_CSV = 'apiNamesCsv';
  @TestVisible
  private static final String MAP_KEY_FIELD_SET_LABEL = 'fieldSetLabel';
  private static final String NAME = 'Name';
  private static final String RECORD_VARIABLE = 'record';
  private static final String STRATEGY_NEWEST = 'Newest';
  private static final String STRATEGY_OLDEST = 'Oldest';
  @TestVisible
  private static final String WARNING_MESSAGE = 'warningMessage';

  private static final String[] EXPECTED_NAME_VALUES = new List<String>{
    NAME, // Most all objects
    'CaseNumber', // Case
    'Subject' // Task
  };
  private static final Map<Schema.DisplayType, String> FIELD_TYPE_MAP = new Map<Schema.DisplayType, String>{
    Schema.DisplayType.DATE => DATE_STRING,
    Schema.DisplayType.DATETIME => DATE_TIME_STRING
  };
  private static final Map<String, String> SYSTEM_FIELDS_MAP = new Map<String, String>{
    CREATED_BY_ID => CREATED_DATE,
    LAST_MODIFIED_BY_ID => LAST_MODIFIED_DATE,
    'CreatedBy.Name' => CREATED_DATE,
    'LastModifiedBy.Name' => LAST_MODIFIED_DATE
  };
  private static final Map<String, String> SYSTEM_FIELDS_LABEL_MAP = new Map<String, String>{
    CREATED_BY_ID => 'Created By',
    LAST_MODIFIED_BY_ID => 'Last Modified By'
  };

  @TestVisible
  private static DynamicFormsController.Interview flowInterview = new DynamicFormsController.Interview();
  @TestVisible
  private static DynamicFormsController.Selector selector = new DynamicFormsController.Selector();

  /**
   * @description - Fetches the metadata of a Layout definition and converts the info into a
   * format that can be utilized by a dynamicFormsFieldSection LWC.
   * @param layoutName - The file name of the Layout metadata configuration
   * @return - The sections of fields to be rendered
   */
  @SuppressWarnings('PMD.CatchSpecificExceptionType')
  @AuraEnabled(cacheable=true)
  public static DynamicFormsController.FieldSection[] getLayoutSectionsByPageLayoutName(
    String layoutName
  ) {
    DynamicFormsController.FieldSection[] sections = new List<DynamicFormsController.FieldSection>();
    if (String.isBlank(layoutName)) {
      return sections;
    }
    try {
      Metadata.Layout layout = selector.getPageLayout(layoutName);
      for (Metadata.LayoutSection section : layout.layoutSections) {
        sections.add(new DynamicFormsController.FieldSection(section));
      }
      return sections;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description - Invokes the flow with the specified API name and returns the value
   * of the `warningMessage` output variable.
   * @param record - The state of the current record including all field values
   * from the database as well as the current pending edits.
   * @param flowApiName - the flow to be invoked.
   * @return any applicable error message from the flow.
   */
  @SuppressWarnings('PMD.CatchSpecificExceptionType')
  @AuraEnabled
  public static String evaluateConditionalWarning(
    SObject record,
    String flowApiName
  ) {
    if (record == null || flowApiName == null) {
      throw new IllegalArgumentException(INVALID_INPUT);
    }
    try {
      flowInterview.createInterview(
        flowApiName,
        new Map<String, Object>{ RECORD_VARIABLE => record }
      );
      flowInterview.start();
    } catch (Exception e) {
      String message = e.getMessage();
      AuraHandledException auraException = new AuraHandledException(message);
      auraException.setMessage(message);
      throw auraException;
    }
    return (String) flowInterview.getVariableValue(WARNING_MESSAGE);
  }

  /**
   * @description - Fetch User Record Access.
   * @param userId - Id of the Logged In user.
   * @param recordId - sObject record Id.
   * @return - UserRecordAccess.
   */
  @AuraEnabled
  public static UserRecordAccess fetchUserRecordAccess(Id userId, Id recordId) {
    try {
      List<UserRecordAccess> userRecordAccessList = selector.getUserRecordAccess(
        userId,
        recordId
      );
      return userRecordAccessList.size() > 0 ? userRecordAccessList[0] : null;
    } catch (System.QueryException e) {
      AuraHandledException ex = new AuraHandledException(e.getMessage());
      ex.setMessage(e.getMessage());
      throw ex;
    }
  }

  /**
   * @description - Fetches comma separated field api names and fieldset label.
   * @param objectApiName - The type of the object.
   * @param fieldSetApiName - The field set api name.
   * @return - Fieldset label to comma separated string representation of field API names.
   */
  @SuppressWarnings(
    'PMD.TryBlocksShouldBeFocused, PMD.CatchSpecificExceptionType'
  )
  @AuraEnabled(cacheable=true)
  public static Map<String, String> getFieldsFromFieldSetAPIName(
    String objectApiName,
    String fieldSetApiName
  ) {
    String fieldSetLabel = '';
    String apiNamesCsv = '';

    try {
      Schema.FieldSet fieldSet = getSObjectTypeByApiName
        .getDescribe()
        .fieldsets.getMap()
        .get(fieldSetApiName);

      fieldSetLabel = fieldSet.getLabel();

      for (Schema.FieldSetMember field : fieldSet.getFields()) {
        apiNamesCsv +=
          (field.getRequired() ? '*' : '') +
          field.getFieldPath() +
          ',';
      }
      apiNamesCsv.removeEnd(',');
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }

    return new Map<String, String>{
      MAP_KEY_FIELD_SET_LABEL => fieldSetLabel,
      MAP_KEY_API_NAMES_CSV => apiNamesCsv
    };
  }

  /**
   * @description - Fetches the metadata for conditional warnings within the system.
   * @param sObjectApiName - The sObject API name for the current record.
   * @return - The configured warnings for this specific sObject.
   */
  @AuraEnabled(cacheable=true)
  public static List<Conditional_Warning__mdt> getWarnings(
    String sObjectApiName
  ) {
    return selector.getWarnings(sObjectApiName);
  }

  /**
   * @description Fetches the record id of a parent record.
   * @param sObjectType - The sObject API name for the current record.
   * @param pathToParentId - The field name for the parent record relationship.
   * @param recordId - The Id of the current record.
   * @return The Id of the parent record.
   */
  @AuraEnabled(cacheable=true)
  public static Id getParentRecordId(
    String sObjectType,
    String pathToParentId,
    Id recordId
  ) {
    SObject result = selector.queryFields(
      pathToParentId,
      sObjectType,
      recordId
    );
    String[] fields = pathToParentId.split(ESCAPED_PERIOD);
    for (Integer i = 0; i < fields.size() - 1; i++) {
      result = result.getSObject(fields[i]);
    }
    return (Id) result.get(fields[fields.size() - 1]);
  }

  /**
   * @description - Fetches the record id of a child record.
   * @param sObjectType - The sObject API name for the current record.
   * @param childRelation - The field name for the child record relationship.
   * @param recordId - The Id of the current record.
   * @param multipleChildrenStrategy - What to do when multiple children exist: Oldest, Newest, None.
   * @return The Id of the child record.
   */
  @SuppressWarnings('PMD.ExcessiveParameterList')
  @AuraEnabled(cacheable=true)
  public static Id getChildRecordId(
    String sObjectType,
    String childRelation,
    Id recordId,
    String multipleChildrenStrategy
  ) {
    String orderBy = multipleChildrenStrategy == STRATEGY_OLDEST
      ? 'ASC'
      : 'DESC';
    String query = String.format(
      '(SELECT Id FROM {0} ORDER BY CreatedDate {1} LIMIT 2)',
      new List<Object>{ childRelation, orderBy }
    );

    SObject result = selector.queryFields(query, sObjectType, recordId);

    // If there are no children, it won't return an empty array, it will be null.
    if (result.getSObjects(childRelation) == null) {
      return null;
    }
    if (
      result.getSObjects(childRelation).size() > 1 &&
      multipleChildrenStrategy != STRATEGY_OLDEST &&
      multipleChildrenStrategy != STRATEGY_NEWEST
    ) {
      throw new AuraHandledException(
        'Unable to render data, multiple child records were found.'
      );
    }
    return (Id) result.getSObjects(childRelation).get(0).get('Id');
  }

  /**
   * @description - Fetches all relevant info needed to render all fields.
   * @param sObjectType - The type of the object.
   * @param fieldDefinitions - The CSV of fields, annotated for special characteristics.
   * @param recordId - The ID of the record. If provided, will perform SOQL for lookup fields.
   * @return - A collection of all relevant information for the requested fields.
   */
  @AuraEnabled(cacheable=true)
  public static DynamicFormsController.Field[] getFieldInfo(
    String sObjectType,
    String fieldDefinitions,
    Id recordId
  ) {
    DynamicFormsController.Field[] fieldList = new List<DynamicFormsController.Field>();
    Map<String, DynamicFormsController.Field> fieldsToQuery = new Map<String, DynamicFormsController.Field>();

    SObjectType schemaType = getSObjectTypeByApiName(sObjectType);
    Map<String, SObjectField> fieldMap = schemaType.getDescribe()
      .fields.getMap();

    for (String fieldDefinition : fieldDefinitions.split(',')) {
      DynamicFormsController.Field field = new DynamicFormsController.Field(
        fieldDefinition,
        fieldMap
      );

      if (!field.isAccessible) {
        continue;
      }

      fieldList.add(field);

      if (field.isReference && recordId != null) {
        fieldsToQuery.put(field.nameReferenceToQuery, field);
      } else if (field.readOnly && recordId != null) {
        fieldsToQuery.put(field.fieldApiName, field);
      }
    }

    if (!fieldsToQuery.isEmpty()) {
      queryFieldValues(fieldsToQuery, sObjectType, recordId);
    }

    return fieldList;
  }

  /**
   * @description - Performs SOQL to get the values of supplied lookup fields.
   * @param fieldsToQuery - Map of query field to Field object to store results.
   * @param sObjectType - The type of the SObject.
   * @param recordId - The ID of the record.
   */
  @SuppressWarnings('PMD.MethodLength')
  private static void queryFieldValues(
    Map<String, DynamicFormsController.Field> fieldsToQuery,
    String sObjectType,
    Id recordId
  ) {
    Set<String> fieldsForQuery = new Set<String>(fieldsToQuery.keySet());

    for (String fieldApiName : SYSTEM_FIELDS_MAP.keySet()) {
      // Here fieldsToQuery map would have CreatedBy.Name/LastModifiedBy.Name.
      if (fieldsForQuery.contains(fieldApiName)) {
        fieldsForQuery.add(SYSTEM_FIELDS_MAP.get(fieldApiName));
      }
    }

    SObject result = selector.queryFields(
      String.join(new List<String>(fieldsForQuery), ','),
      sObjectType,
      recordId
    );

    for (String lookupName : fieldsToQuery.keySet()) {
      DynamicFormsController.Field field = fieldsToQuery.get(lookupName);

      if (field.isReference) {
        String[] fieldComponents = lookupName.split(ESCAPED_PERIOD);
        field.referenceName = (String) result
          ?.getSObject(fieldComponents[0])
          ?.get(fieldComponents[1]);
        field.referenceValue = (String) result?.get(field.fieldApiName);

        if (field.isSystemField) {
          // Here field would have CreatedById/LastModifiedById as field Api Names.
          field.systemDateValue = DateTime.valueOf(
              result?.get(SYSTEM_FIELDS_MAP.get(field.fieldApiName))
            )
            .format();

          // Default field label of system fields are Created By Id/Last Modified By Id
          // thus have to override it
          field.fieldLabel = SYSTEM_FIELDS_LABEL_MAP.get(field.fieldApiName);
          field.readOnlyValue =
            field.referenceName +
            ', ' +
            field.systemDateValue;
        }
      } else if (field.readOnly) {
        if (result?.get(field.fieldApiName) == null) {
          field.readOnlyValue = '';
          continue;
        }
        // format Date/DateTime readonly non reference field's values
        if (field.fieldType == DATE_STRING) {
          field.readOnlyValue = Date.valueOf(result?.get(field.fieldApiName))
            .format();
        } else if (field.fieldType == DATE_TIME_STRING) {
          field.readOnlyValue = DateTime.valueOf(
              result?.get(field.fieldApiName)
            )
            .format();
        } else {
          field.readOnlyValue = String.valueOf(result?.get(field.fieldApiName));
        }
      }
    }
  }

  /**
   * @description - Returns the type of object to lookup field references.
   * @param field - The FieldDescribe of the field.
   * @return The parent Object of a lookup.
   */
  private static String getLookupObject(DescribeFieldResult field) {
    // Don't support polymorphic fields, return unsupported User object name
    return field.getReferenceTo().size() > 1
      ? 'User'
      : '' + field.getReferenceTo()[0];
  }

  /**
   * @description - Returns the reference to the lookup field's Name field.
   * @param field - The FieldDescribe of the field.
   * @return The name field of the parent sObject.
   */
  private static String getNameReference(DescribeFieldResult field) {
    String relationshipName = field.getRelationshipName();
    List<Schema.sObjectType> referenceTo = field.getReferenceTo();
    String objectName = referenceTo.size() > 1
      ? NAME
      : getNameField(referenceTo[0]);
    return relationshipName + '.' + objectName;
  }

  /**
   * @description - Returns the api name of the Name field of a given SObject
   * @param sObjectType - The type of sObject.
   * @return - The API name of the name field of the parent sObject
   */
  private static String getNameField(Schema.sObjectType sObjectType) {
    Map<String, SObjectField> fieldsMap = sObjectType.getDescribe(
        SObjectDescribeOptions.DEFERRED
      )
      .fields.getMap();

    // We expect most all objects to include a standard name field, but verify first.
    for (String expectedNameField : EXPECTED_NAME_VALUES) {
      if (
        fieldsMap.containsKey(expectedNameField) &&
        fieldsMap.get(expectedNameField).getDescribe().isNameField()
      ) {
        return expectedNameField;
      }
    }

    // If a non-standard name field is present, iterate the whole list to find it.
    for (SObjectField fieldToken : fieldsMap.values()) {
      DescribeFieldResult fieldDescribe = fieldToken.getDescribe();

      if (fieldDescribe.isNameField()) {
        return fieldDescribe.getName();
      }
    }

    return null;
  }

  /**
   * @description - Metadata about a LayoutSection recorded in a format that can be utilized by a
   * dynamicFormsFieldSection LWC.
   */
  public class FieldSection {
    /**
     * @description - API names of the fields in this layout section.
     *   - Prepend with '*' to mark as required.
     *   - Append with '*' to mark as read-only.
     *   - Insert an extra comma to insert a blank space
     */
    @AuraEnabled
    public String apiNamesCsv { get; set; }

    /**
     * @description - The number of columns to render.
     * @note - Despite being a number, dynamicFormsFieldSection expects this as a String.
     */
    @AuraEnabled
    public String numberOfColumns { get; set; }

    /**
     * @description - The label of the section.
     */
    @AuraEnabled
    public String sectionLabel { get; set; }

    /**
     * @description - Constructor
     * @param section - Section from the Metadata API.
     */
    public FieldSection(Metadata.LayoutSection section) {
      sectionLabel = section.label;
      numberOfColumns = String.valueOf(section.layoutColumns.size());

      Metadata.LayoutItem[] items = zipColumns(section.layoutColumns);
      String[] apiNames = new List<String>();
      for (Metadata.LayoutItem item : items) {
        apiNames.add(convertLayoutItem(item));
      }

      apiNamesCsv = String.join(apiNames, ',');
    }

    /**
     * @description - Converts multiple lists of LayoutItems into a zipped list.
     * @param columns - The list of LayoutColumns as defined in a LayoutSection.
     * @return -
     * Example: [1, 2, 3, 4], [5, 6] -> [1, 5, 2, 6, 3, 4]
     */
    private Metadata.LayoutItem[] zipColumns(
      List<Metadata.LayoutColumn> columns
    ) {
      Metadata.LayoutItem[] items = new List<Metadata.LayoutItem>();
      Integer maxSize = 0;

      for (Metadata.LayoutColumn column : columns) {
        if (column.layoutItems != null) {
          maxSize = Math.max(maxSize, column.layoutItems.size());
        }
      }

      for (Integer i = 0; i < maxSize; i++) {
        for (Metadata.LayoutColumn column : columns) {
          if (column.layoutItems != null && i < column.layoutItems.size()) {
            items.add(column.layoutItems[i]);
          }
        }
      }

      return items;
    }

    /**
     * @description - Converts a LayoutItem into the format expected for apiNames LWC:
     *   - Prepend with '*' to mark as required.
     *   - Append with '*' to mark as read-only.
     *   - Insert an extra comma to insert a blank space
     * @param item - LayoutItem to convert.
     * @return - String value representation.
     */
    private String convertLayoutItem(Metadata.LayoutItem item) {
      switch on item.behavior {
        when REQUIRED {
          return '*' + item.field;
        }
        when READONLY {
          return item.field + '*';
        }
        when EDIT {
          return item.field;
        }
        // Behavior can be null for emptySpace or unsupported types such as canvas/component.
        when else {
          return '';
        }
      }
    }
  }

  /**
   * @description - Metadata about a LayoutSection recorded in a format that can be utilized by a
   * dynamicFormsFieldSection LWC.
   */
  @SuppressWarnings('PMD.NcssConstructorCount, PMD.ApexDoc')
  public class Field {
    public Boolean isAccessible = true;

    public String nameReferenceToQuery;

    @AuraEnabled
    public Boolean isCalculated { get; set; }

    @AuraEnabled
    public Boolean isReference { get; set; }

    @AuraEnabled
    public Boolean isSpace { get; set; }

    @AuraEnabled
    public Boolean isSystemField { get; set; }

    @AuraEnabled
    public Boolean readOnly { get; set; }

    @AuraEnabled
    public Boolean required { get; set; }

    @AuraEnabled
    public String fieldApiName { get; set; }

    // Only necessary for Reference fields
    @AuraEnabled
    public String fieldLabel { get; set; }

    @AuraEnabled
    public String fieldType { get; set; }

    @AuraEnabled
    public String helpText { get; set; }

    @AuraEnabled
    public String readOnlyValue { get; set; }

    // Only necessary for Reference fields
    @AuraEnabled
    public String referenceName { get; set; }

    // Only necessary for Reference fields
    @AuraEnabled
    public String referenceObject { get; set; }

    // Only necessary for Reference fields
    @AuraEnabled
    public String referenceValue { get; set; }

    @AuraEnabled
    public String systemDateValue { get; set; }

    public Field(
      String fieldSpecification,
      Map<String, SObjectField> fieldMap
    ) {
      this.isSpace = String.isBlank(fieldSpecification);
      if (this.isSpace) {
        this.required = false;
        this.readOnly = false;
        this.isReference = false;
        return;
      }

      String trimmedField = fieldSpecification.trim();
      this.fieldApiName = trimmedField.replace('*', '');
      this.required = trimmedField.startsWith('*');
      this.readOnly = trimmedField.endsWith('*') && !this.required;
      this.isSystemField = false;
      
      // Here field would have CreatedById/LastModifiedById as field Api Names.
      if (SYSTEM_FIELDS_MAP.containsKey(this.fieldApiName)) {
        this.isSystemField = true;
        this.readOnly = true;
      }

      DescribeFieldResult fieldResult = fieldMap.get(fieldApiName)
        ?.getDescribe();
      if (fieldResult == null || !fieldResult.isAccessible()) {
        this.isAccessible = false;
        return;
      }

      this.fieldLabel = fieldResult.getLabel();
      this.helpText = fieldResult.getInlineHelpText();
      this.fieldType = FIELD_TYPE_MAP.get(fieldResult.getType());
      this.isCalculated = fieldResult.isCalculated();

      if (fieldResult.getType() == Schema.DisplayType.REFERENCE) {
        this.isReference = true;
        this.nameReferenceToQuery = getNameReference(fieldResult);
        this.referenceObject = getLookupObject(fieldResult);
      } else {
        this.isReference = false;
      }
    }
  }

  /**
   * @description - Enables the mocking of a flow interview
   */
  public virtual class Interview {
    @TestVisible
    protected Flow.Interview instance;

    /**
     * @description - Creates an interview.
     * @param flowApiName - API name of the autolaunched flow to be
     * dynamically instantiated.
     * @param inputs - Inputs to the flow.
     */
    public virtual void createInterview(
      String flowApiName,
      Map<String, Object> inputs
    ) {
      this.instance = Flow.Interview.createInterview(flowApiName, inputs);
    }

    /**
     * @description - Starts the interview.
     */
    public virtual void start() {
      this.instance.start();
    }

    /**
     * @description - Retrieves the value of an output variable from the flow.
     * @param variableName - API name of the variable within the flow.
     * @return - the output variable's value.
     */
    public virtual Object getVariableValue(String variableName) {
      return this.instance.getVariableValue(variableName);
    }
  }

  @TestVisible
  @SuppressWarnings('PMD.ApexCRUDViolation')
  private inherited sharing virtual class Selector {
    /**
     * @description - Fetches the metadata for conditional warnings within the system.
     * @param sObjectApiName - The sObject API name for the current record.
     * @return - Conditional warning metadata.
     */
    public virtual Conditional_Warning__mdt[] getWarnings(
      String sObjectApiName
    ) {
      return [
        SELECT MasterLabel, Flow_API_Name__c
        FROM Conditional_Warning__mdt
        WHERE SObject_API_Name__c = :sObjectApiName
      ];
    }

    /**
     * @description - Fetches the metadata of a Layout definition as defined exactly in source XML.
     * @param layoutName - exact filename in source (i.e. 'Case-Service').
     * @return - The layout with the provided API name.
     */
    public virtual Metadata.Layout getPageLayout(String layoutName) {
      List<Metadata.Metadata> layouts = Metadata.Operations.retrieve(
        Metadata.MetadataType.Layout,
        new List<String>{ layoutName }
      );
      return layouts.isEmpty()
        ? new Metadata.Layout()
        : (Metadata.Layout) layouts[0];
    }

    /**
     * @description - Performs a SOQL query for a list of fields to lookup.
     * @param queryFields - The list of fields being queried.
     * @param sObjectType - The type of SObject.
     * @param recordId - The id of the record.
     * @return - The query result.
     */
    @SuppressWarnings('PMD.ApexSOQLInjection')
    public virtual SObject queryFields(
      String queryFields,
      String sObjectType,
      Id recordId
    ) {
      String query =
        ' SELECT ' +
        queryFields +
        ' FROM ' +
        sObjectType +
        ' WHERE Id = :recordId LIMIT 1';
      return Database.query(query);
    }

    /**
     * @description Performs a SOQL query for user record access check.
     * @param userId - Id of the Logged In user.
     * @param recordId - sObject record Id.
     * @return - Query result.
     */
    public virtual List<UserRecordAccess> getUserRecordAccess(
      Id userId,
      Id recordId
    ) {
      return [
        SELECT RecordId, HasEditAccess
        FROM UserRecordAccess
        WHERE UserId = :userId AND RecordId = :recordId
        LIMIT 1
      ];
    }
  }
  
  private Schema.SObjectType getSObjectTypeByApiName(String sobjectApiName) {
    return Schema.describeSObjects(new String[] {sobjectApiName});
  }
}